version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update environment
          command: |
            rustup component add rustfmt
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Test
          command: cargo test

